=== COMP4711Lab6/Timetable/Data/timetable.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Root Element -->
<!ELEMENT schedule (courses, days)>

<!-- Courses -->
<!ELEMENT courses (course)>
<!ELEMENT course (booking)>
<!ATTLIST course code #REQUIRED>

<!-- Days -->
<!ELEMENT days (day)>
<!ELEMENT day (booking*)>
<!ATTLIST day type #REQUIRED>

<!-- Bookings -->
<!ELEMENT booking (instructor, room, bookingtype, timeslot?, coursename?)>
<!ELEMENT instructor (#PCDATA)>
<!ELEMENT room (#PCDATA)>
<!ELEMENT bookingtype (#PCDATA)>
<!ELEMENT timeslot (#PCDATA)>
<!ELEMENT coursename (#PCDATA)>

=== COMP4711Lab6/Timetable/Data/courses.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE courses SYSTEM "timetable.dtd">
<courses>
    <course code="BLAW 3600">
        <booking>
            <instructor>Catherine Ryan</instructor>
            <room>SW3 4785</room>
            <bookingtype>Lab</bookingtype>
        </booking>
    </course>

    <course code="COMP 4735">
        <booking>
            <instructor>Mirela Gutica</instructor>
            <room>SW1 1205</room>
            <bookingtype>Lecture</bookingtype>
        </booking>
    </course>

    <course code="COMP 4735">
        <booking>
            <instructor>Mirela Gutica</instructor>
            <room>SE12 320</room>
            <bookingtype>Lab</bookingtype>
        </booking>
    </course>

    <course code="COMP 4735">
        <booking>
            <instructor>Mirela Gutica</instructor>
            <room>SW1 1205</room>
            <bookingtype>Lecture</bookingtype>
        </booking>
    </course>

    <course code="COMP 4977">
        <booking>
            <instructor>D'Arcy Smith</instructor>
            <room>SW12 325</room>
            <bookingtype>Seminar</bookingtype>
        </booking>
    </course>

    <course code="COMP 4560">
        <booking>
            <instructor>Branda Fine</instructor>
            <room>SW5 1850</room>
            <bookingtype>Lecture</bookingtype>
        </booking>
    </course>

    <course code="COMP 4711">
        <booking>
            <instructor>James Parry</instructor>
            <room>SW5 1840</room>
            <bookingtype>Lecture</bookingtype>
        </booking>
    </course>


    <course code="COMP 4560">
        <booking>
            <instructor>Joseph Lo</instructor>
            <room>SE12 322</room>
            <bookingtype>Lab</bookingtype>
        </booking>
    </course>

    <course code="COMP 4711">
        <booking>
            <instructor>James Parry</instructor>
            <room>SE12 320</room>
            <bookingtype>Lab</bookingtype>
        </booking>
    </course>

    <course code="COMP 4976">
        <booking>
            <instructor>Medhat Elmasry</instructor>
            <room>SE12 308</room>
            <bookingtype>Seminar</bookingtype>
        </booking>
    </course>

    <course code="COMP 4735">
        <booking>
            <instructor>Mirela Gutica</instructor>
            <room>SW3 1710</room>
            <bookingtype>Lecture</bookingtype>
        </booking>
    </course>

    <course code="BLAW 3600">
        <booking>
            <instructor>Catherine Ryan</instructor>
            <room>SW5 1840</room>
            <bookingtype>Lecture</bookingtype>
        </booking>
    </course>

    <course code="COMP 4560">
        <booking>
            <instructor>Catherine Ryan</instructor>
            <room>SW3 1750</room>
            <bookingtype>Lecture</bookingtype>
        </booking>
    </course>



</courses>

=== COMP4711Lab6/Timetable/Data/days.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE days SYSTEM "timetable.dtd">
<days>
    <day type="Monday">
        <booking>
            <instructor>Catherine Ryan</instructor>
            <room>SW3 4785</room>
            <bookingtype>Lab</bookingtype>
            <timeslot>930</timeslot>
            <coursename>BLAW 3600</coursename>
        </booking>

        <booking>
            <instructor>Mirela Gutica</instructor>
            <room>SW1 1205</room>
            <bookingtype>Lecture</bookingtype>
            <timeslot>1130</timeslot>
            <coursename>COMP 4735</coursename>
        </booking>

        <booking>
            <instructor>Mirela Gutica</instructor>
            <room>SE12 320</room>
            <bookingtype>Lab</bookingtype>
            <timeslot>1230</timeslot>
            <coursename>COMP 4735</coursename>
        </booking>
    </day>

    <day type="Tuesday">
        <booking>
            <instructor>D'Arcy Smith</instructor>
            <room>SE12 325</room>
            <bookingtype>Seminar</bookingtype>
            <timeslot>830</timeslot>
            <coursename>COMP 4977</coursename>
        </booking>

        <booking>
            <instructor>Brenda Fine</instructor>
            <room>SW5 1850</room>
            <bookingtype>Lecture</bookingtype>
            <timeslot>1130</timeslot>
            <coursename>COMP 4560</coursename>
        </booking>

        <booking>
            <instructor>James Parry</instructor>
            <room>SW5 1840</room>
            <bookingtype>Lecture</bookingtype>
            <timeslot>1430</timeslot>
            <coursename>COMP 4711</coursename>
        </booking>

        <booking>
            <instructor>Joseph Lo</instructor>
            <room>SE12 322</room>
            <bookingtype>Lab</bookingtype>
            <timeslot>1530</timeslot>
            <coursename>COMP 4560</coursename>
        </booking>
    </day>

    <day type="Wednesday">
        <booking>
            <instructor>James Parry</instructor>
            <room>SE12 322</room>
            <bookingtype>Lab</bookingtype>
            <timeslot>930</timeslot>
            <coursename>COMP 4711</coursename>
        </booking>

        <booking>
            <instructor>Mirela Gutica</instructor>
            <room>SW1 1205</room>
            <bookingtype>Lecture</bookingtype>
            <timeslot>1330</timeslot>
            <coursename>COMP 4735</coursename>
        </booking>
    </day>

    <day type="Thursday">
        <booking>
            <instructor>Medhat Elmasry</instructor>
            <room>SE12 308</room>
            <bookingtype>Seminar</bookingtype>
            <timeslot>830</timeslot>
            <coursename>COMP 4976</coursename>
        </booking>

        <booking>
            <instructor>Mirela Gutica</instructor>
            <room>SW3 1710</room>
            <bookingtype>Lecture</bookingtype>
            <timeslot>1130</timeslot>
            <coursename>COMP 4735</coursename>
        </booking>

        <booking>
            <instructor>Medhat Elmasry</instructor>
            <room>SE12 308</room>
            <bookingtype>Seminar</bookingtype>
            <timeslot>1230</timeslot>
            <coursename>COMP 4976</coursename>
        </booking>
    </day>

    <day type="Friday">
        <booking>
            <instructor>Catherine Ryan</instructor>
            <room>SW5 1840</room>
            <bookingtype>Lecture</bookingtype>
            <timeslot>830</timeslot>
            <coursename>BLAW 3600</coursename>
        </booking>

        <booking>
            <instructor>Medhat Elmasry</instructor>
            <room>SE12 308</room>
            <bookingtype>Seminar</bookingtype>
            <timeslot>1030</timeslot>
            <coursename>COMP 4976</coursename>
        </booking>

        <booking>
            <instructor>Brenda Fine</instructor>
            <room>SE12 308</room>
            <bookingtype>Lecture</bookingtype>
            <timeslot>1230</timeslot>
            <coursename>COMP 4560</coursename>
        </booking>

        <booking>
            <instructor>D'Arcy Smith</instructor>
            <room>SE12 325</room>
            <bookingtype>Seminar</bookingtype>
            <timeslot>1430</timeslot>
            <coursename>COMP 4977</coursename>
        </booking>
    </day>
</days>
