=== COMP4711Lab6/Timetable/data/timetable.dtd
<!ELEMENT schedule (daysofweek,courses,periods)>
        <!ELEMENT periods (timeslot*)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT term (#PCDATA)>
        <!ELEMENT set (#PCDATA)>
        <!ELEMENT daysofweek (day*) >
        <!ELEMENT day (booking*)>
        <!ATTLIST day name CDATA #REQUIRED>
        <!ELEMENT courses (course*)>
        <!ELEMENT course (booking*)>
        <!ATTLIST course name CDATA #REQUIRED>
        <!ELEMENT timeslot (booking*)>
        <!ATTLIST timeslot time CDATA #REQUIRED>
        <!ELEMENT booking (dayofweek?, coursename?, teacher, location, classtype)>
        <!ATTLIST booking day CDATA #IMPLIED time CDATA #IMPLIED>
        <!ELEMENT dayofweek (#PCDATA)>
        <!ELEMENT coursename (#PCDATA)>
        <!ELEMENT teacher (#PCDATA)>
        <!ELEMENT location (#PCDATA)>
        <!ELEMENT classtype (#PCDATA)>

=== COMP4711Lab6/Timetable/data/timetable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schedule SYSTEM "timetable.dtd">
<schedule>
    <daysofweek>
        <day name="Monday">
            <booking time="9:30-11:20">
                <coursename>BLAW 3600</coursename>
                <teacher>Catherine Ryan</teacher>
                <location>SW3 4785</location>
                <classtype>Lab</classtype>
            </booking>
            <booking time="11:30-12:20">
                <coursename>COMP 4735</coursename>
                <teacher>Mirela Gutica</teacher>
                <location>SW1 4735</location>
                <classtype>Lecture</classtype>
            </booking>
            <booking time="12:30-14:20">
                <coursename>COMP 4735</coursename>
                <teacher>Mirela Gutica</teacher>
                <location>SE12 320</location>
                <classtype>Lab</classtype>
            </booking>
        </day>
        <day name="Tuesday">
            <booking time="8:30-10:20">
                <coursename>COMP 4977</coursename>
                <teacher>D'Arcy Smith</teacher>
                <location>SE12 325</location>
                <classtype>Lab</classtype>
            </booking>
            <booking time="11:30-12:20">
                <coursename>COMP 4560</coursename>
                <teacher>Brenda Fine</teacher>
                <location>SW5 1850</location>
                <classtype>Lecture</classtype>
            </booking>
            <booking time="14:30-15:20">
                <coursename>COMP 4711</coursename>
                <teacher>Jim Parry</teacher>
                <location>SW5 1840</location>
                <classtype>Lecture</classtype>
            </booking>
            <booking time="15:30-17:20">
                <coursename>COMP 4560</coursename>
                <teacher>Joseph Lo</teacher>
                <location>SE12 322</location>
                <classtype>Lab</classtype>
            </booking>
        </day>
        <day name="Wednesday">
            <booking time="9:30-11:20">
                <coursename>COMP 4711</coursename>
                <teacher>Jim Parry</teacher>
                <location>SE12 320</location>
                <classtype>Lab</classtype>
            </booking>
            <booking time="13:30-14:20">
                <coursename>COMP 4735</coursename>
                <teacher>Mirela Gutica</teacher>
                <location>SW1 1205</location>
                <classtype>Lecture</classtype>
            </booking>
        </day>
        <day name="Thursday">
            <booking time="8:30-10:20">
                <coursename>COMP 4976</coursename>
                <teacher>Medhat Elmasry</teacher>
                <location>SE12 308</location>
                <classtype>Lab</classtype>
            </booking>
            <booking time="11:30-12:20">
                <coursename>COMP 4735</coursename>
                <teacher>Mirela Gutica</teacher>
                <location>SW3 1710</location>
                <classtype>Lecture</classtype>
            </booking>
            <booking time="12:30-13:20">
                <coursename>COMP 4976</coursename>
                <teacher>Medhat Elmasry</teacher>
                <location>SE12 308</location>
                <classtype>Lab</classtype>
            </booking>
        </day>

        <day name="Friday">
            <booking time="8:30-10:20">
                <coursename>BLAW 3600</coursename>
                <teacher>Catherine Ryan</teacher>
                <location>SW5 1840</location>
                <classtype>Lecture</classtype>
            </booking>
            <booking time="10:30-12:20">
                <coursename>COMP 4976</coursename>
                <teacher>Medhat Elmasry</teacher>
                <location>SE12 308</location>
                <classtype>Lab</classtype>
            </booking>
            <booking time="12:30-13:20">
                <coursename>COMP 4560</coursename>
                <teacher>Brenda Fine</teacher>
                <location>SW3 1750</location>
                <classtype>Lecture</classtype>
            </booking>
            <booking time="14:30-17:20">
                <coursename>COMP 4977</coursename>
                <teacher>D'Arcy Smith</teacher>
                <location>SE12 325</location>
                <classtype>Lab</classtype>
            </booking>
        </day>
    </daysofweek>
    <courses>
        <course name="BLAW 3600">
            <booking time="9:30-11:20">
                <dayofweek>Monday</dayofweek>
                <teacher>Catherine Ryan</teacher>
                <location>SW1 4785</location>
                <classtype>Lab</classtype>
            </booking>
            <booking time="8:30-10:20">
                <dayofweek>Friday</dayofweek>
                <teacher>Catherine Ryan</teacher>
                <location>SW5 1840</location>
                <classtype>Lecture</classtype>
            </booking>
        </course>
        <course name="COMP 4735">
            <booking time="11:30-12:20">
                <dayofweek>Monday</dayofweek>
                <teacher>Mirela Gutica</teacher>
                <location>SW1 1205</location>
                <classtype>Lecture</classtype>
            </booking>
            <booking time="12:30-14:20">
                <dayofweek>Monday</dayofweek>
                <teacher>Mirela Gutica</teacher>
                <location>SE12 320</location>
                <classtype>lab</classtype>
            </booking>
            <booking time="13:30-14:20">
                <dayofweek>Wednesday</dayofweek>
                <teacher>Mirela Gutica</teacher>
                <location>SW1 1205</location>
                <classtype>lecture</classtype>
            </booking>
            <booking time="11:30-12:20">
                <dayofweek>Thursday</dayofweek>
                <teacher>Mirela Gutica</teacher>
                <location>SW3 1710</location>
                <classtype>lecture</classtype>
            </booking>
        </course>
        <course name="COMP 4977">
            <booking time="8:30-10:20">
                <dayofweek>Tuesday</dayofweek>
                <teacher>D'arcy Smith</teacher>
                <location>SE12 325</location>
                <classtype>seminar</classtype>
            </booking>
            <booking time="14:30-17:20">
                <dayofweek>Friday</dayofweek>
                <teacher>D'arcy Smith</teacher>
                <location>SE12 325</location>
                <classtype>seminar</classtype>
            </booking>
        </course>
        <course name="COMP 4560">
            <booking time="11:30-12:20">
                <dayofweek>Tuesday</dayofweek>
                <teacher>Brenda Fine</teacher>
                <location>SW5 1850</location>
                <classtype>Lecture</classtype>
            </booking>
            <booking time="15:30-17:20">
                <dayofweek>Tuesday</dayofweek>
                <teacher>Joseph Lo</teacher>
                <location>SE12 320</location>
                <classtype>lab</classtype>
            </booking>
            <booking time="12:30-13:20">
                <dayofweek>Friday</dayofweek>
                <teacher>Brenda Fine</teacher>
                <location>SW3 1750</location>
                <classtype>lecture</classtype>
            </booking>
        </course>
        <course name="COMP 4711">
            <booking time="14:30-15:20">
                <dayofweek>Tuesday</dayofweek>
                <teacher>Jim Parry</teacher>
                <location>SW1 1840</location>
                <classtype>Lecture</classtype>
            </booking>
            <booking time="9:30-11:20">
                <dayofweek>Wednesday</dayofweek>
                <teacher>Jim Parry</teacher>
                <location>SE12 320</location>
                <classtype>lab</classtype>
            </booking>
        </course>
        <course name="COMP 4976">
            <booking time="8:30-10:20">
                <dayofweek>Thursday</dayofweek>
                <teacher>Medhat Elmasry</teacher>
                <location>SE12 308</location>
                <classtype>Seminar</classtype>
            </booking>
            <booking time="12:30-13:20">
                <dayofweek>Thursday</dayofweek>
                <teacher>Medhat Elmasry</teacher>
                <location>SE12 308</location>
                <classtype>Seminar</classtype>
            </booking>
            <booking time="10:30-12:20">
                <dayofweek>Friday</dayofweek>
                <teacher>Medhat Elmasry</teacher>
                <location>SE12 308</location>
                <classtype>Seminar</classtype>
            </booking>
        </course>
    </courses>
    <periods>
        <timeslot time="8:30-10:20">
            <booking day="Tuesday">
                <coursename>COMP 4977</coursename>
                <teacher>D'Arcy Smith</teacher>
                <location>SE12 325</location>
                <classtype>Seminar</classtype>
            </booking>
            <booking day="Tuesday">
                <coursename>COMP 4976</coursename>
                <teacher>Medhat Elmasry</teacher>
                <location>SE12 312</location>
                <classtype>Seminar</classtype>
            </booking>
            <booking day="Friday">
                <coursename>BLAW 3600</coursename>
                <teacher>Catherine</teacher>
                <location>SW5 1840</location>
                <classtype>Lecture</classtype>
            </booking>
        </timeslot>
        <timeslot time="9:30-11:20">
            <booking day="Monday">
                <coursename>BLAW 3600</coursename>
                <teacher>Catherine</teacher>
                <location>SW3 4785</location>
                <classtype>Lab</classtype>
            </booking>
            <booking day="Wednesday">
                <coursename>COMP 4711</coursename>
                <teacher>Jim Parry</teacher>
